modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "${mod_issues_link}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
displayURL="${mod_website_link}"
logoFile = "icon.png"
credits = ""
authors = "mcrobertx22"
description = '''
Spawners now have a cooldown.
'''
[[dependencies.temporary_spawners]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.temporary_spawners]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"